---
#SPDX-License-Identifier: MIT
# VM Lifecycle Role - Metadata

galaxy_info:
  role_name: vm_lifecycle
  namespace: sombrero_edge
  author: Sombrero Edge Control Infrastructure Team
  description: |
    Comprehensive VM lifecycle management including rollback operations, cleanup
    automation, reset procedures, and infrastructure state management. Provides
    systematic approaches to infrastructure recovery and maintenance operations.

  company: Sombrero Edge Control
  license: MIT

  min_ansible_version: "2.15"

  # Platform support
  platforms:
    - name: Ubuntu
      versions:
        - "20.04"
        - "22.04"
        - "24.04"
    - name: Debian
      versions:
        - "11"
        - "12"
    - name: CentOS
      versions:
        - "8"
        - "9"
    - name: RedHat
      versions:
        - "8"
        - "9"
    - name: Fedora
      versions:
        - "39"
        - "40"
    - name: MacOSX
      versions:
        - "13"
        - "14"
    - name: Darwin
      versions:
        - "22"
        - "23"

  galaxy_tags:
    - lifecycle
    - rollback
    - cleanup
    - terraform
    - infrastructure
    - automation
    - devops
    - vm
    - management
    - recovery
    - state
    - provisioning
    - maintenance

# Role Dependencies
dependencies: []

# Collection Requirements
collections:
  - ansible.builtin
  - community.general
  - ansible.posix

# Role Compatibility Notes:
# - Designed for infrastructure lifecycle management
# - Requires Terraform/OpenTofu CLI for state operations
# - Supports both local and remote state backends
# - Cross-platform compatibility for control nodes
# - Safe operation defaults with confirmation requirements
# - Comprehensive backup and recovery capabilities

# Integration Requirements:
# - Terraform or OpenTofu CLI installed
# - SSH client for known_hosts management
# - File system access for backup operations
# - Network access for remote state backends (if used)
# - Appropriate permissions for resource management

# Safety Features:
# - Confirmation prompts for destructive operations
# - Backup creation before major changes
# - Resource preservation options
# - Dry-run mode for testing
# - Comprehensive logging and reporting
# - Recovery mechanisms for failed operations

# Performance Characteristics:
# - Operations prioritize safety over speed
# - Backup operations may be time-intensive
# - Network timeouts configured for reliability
# - Resource cleanup optimized for completeness
# - Parallel operations limited for safety
