# cloud-config
hostname: jump-man
manage_etc_hosts: true
preserve_hostname: false

# Create ansible user with SSH access only
users:
  - name: ansible
    groups: sudo
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: true
    ssh_authorized_keys:
      - ${ssh_authorized_key}

# Minimal network configuration
write_files:
  - path: /etc/netplan/99-static.yaml
    content: |
      network:
        version: 2
        ethernets:
          ens18:
            addresses: [192.168.10.250/24]
            gateway4: 192.168.10.1
            nameservers:
              addresses: [1.1.1.1, 1.0.0.1]

# Apply network configuration
runcmd:
  - netplan apply

# Remove all package installations
# Remove all script downloads and executions
# Remove firewall configuration
# Remove Docker installation
