---
# Firewall role variables (higher precedence than defaults)

# Docker security presets (optional convenience configurations)
firewall_docker_security_presets: []
# Available presets:
# - block_external: Block all external access to containers
# - allow_web: Allow HTTP/HTTPS to containers
# - allow_trusted: Allow trusted networks to access containers

# System requirements
firewall_minimum_kernel_version: "3.10"

# iptables table names
firewall_tables:
  - filter
  - nat
  - mangle
  - raw

# Standard chains that should never be deleted
firewall_protected_chains:
  - INPUT
  - OUTPUT
  - FORWARD
  - PREROUTING
  - POSTROUTING
  - DOCKER
  - DOCKER-USER
  - DOCKER-ISOLATION-STAGE-1
  - DOCKER-ISOLATION-STAGE-2

# Required kernel modules
firewall_required_modules:
  - ip_tables
  - iptable_filter
  - iptable_nat
  - iptable_mangle
  - ip_conntrack
  - iptable_raw
  - nf_conntrack
  - nf_conntrack_ipv4
  - nf_nat
  - nf_nat_ipv4

# Docker-specific chains to check
firewall_docker_chains:
  - DOCKER
  - DOCKER-USER
  - DOCKER-ISOLATION-STAGE-1
  - DOCKER-ISOLATION-STAGE-2

# Common service ports
firewall_common_ports:
  ssh: 22
  http: 80
  https: 443
  smtp: 25
  dns: 53
  ntp: 123
  mysql: 3306
  postgresql: 5432
  redis: 6379
  elasticsearch: 9200
  mongodb: 27017

# Rate limit defaults
firewall_rate_limits:
  ssh: "5/minute"
  http: "100/second"
  https: "100/second"
  api: "50/second"
  default: "10/second"
