# MegaLinter Configuration for Sombrero Edge Control
# Central configuration file for all linting rules and settings

# Project information
project:
  name: Sombrero-Edge-Control
  tz: America/New_York
  adrFolder: ./docs/decisions

# Enable specific linters for IaC + docs
ENABLE_LINTERS:
  - MARKDOWN_MARKDOWNLINT
  # - MARKDOWN_MARKDOWN_LINK_CHECK  # Can be slow, disabled for speed
  - TERRAFORM_TFLINT
  - TERRAFORM_TERRAFORM_FMT
  # - TERRAFORM_TERRASCAN  # Can be slow, disabled for speed
  # - ANSIBLE_ANSIBLE_LINT  # Temporarily disabled due to structural issues
  - YAML_YAMLLINT
  - JSON_ESLINT_PLUGIN_JSONC
  - BASH_SHFMT

# Global include/exclude filters
FILTER_REGEX_INCLUDE: "docs/|README.md|infrastructure/|ansible/|packer/"
FILTER_REGEX_EXCLUDE: '(\.git/|\.github/|node_modules/|build/|dist/|vendor/|\.terraform/)'

# Keep rules in-repo for portability
LINTER_RULES_PATH: .github/linters

# Reporter and output settings
REPORT_OUTPUT_FOLDER: report
PRINT_ALPACA: false
SHOW_SKIPPED_LINTERS: true
VALIDATE_ALL_CODEBASE: true

# SARIF reporting for GitHub Security tab
SARIF_REPORTER: true

# Auto-fix settings (disabled by default for safety)
APPLY_FIXES: none
APPLY_FIXES_EVENT: pull_request
APPLY_FIXES_MODE: pull_request
APPLY_FIXES_IF: modified
APPLY_FIXES_IF_SARIF: error

# Non-blocking mode for gradual adoption
DISABLE_ERRORS: true  # Report errors but don't fail the build
FAIL_IF_MISSING_LINTER_IN_FLAVOR: false  # Don't fail if a linter is missing

# Optional: Set thresholds for when to start failing (uncomment to use)
# DISABLE_ERRORS_IF_LESS_THAN: 500  # Fail only if errors exceed this number

# Terraform-specific settings
TERRAFORM_TFLINT_CONFIG_FILE: .tflint.hcl
TERRAFORM_TERRASCAN_CONFIG_FILE: .terrascan.toml
TERRAFORM_TFLINT_UNSECURED_ENV_VARIABLES: GITHUB_TOKEN

# Ansible-specific settings
ANSIBLE_ANSIBLE_LINT_CONFIG_FILE: .ansible-lint

# Disable slow or problematic linters
DISABLE_LINTERS:
  - SPELL_CSPELL  # Too many false positives in IaC
  - TERRAFORM_TERRASCAN  # Can timeout in CI
  - MARKDOWN_MARKDOWN_LINK_CHECK  # External links can fail randomly

LLM_ADVISOR_ENABLED: true
LLM_PROVIDER: anthropic
LLM_MODEL_NAME: claude-3-7-sonnet-latest
LLM_MAX_TOKENS: 1000
LLM_TEMPERATURE: 0.1
