# Configuration file for MegaLinter
#
# See all available variables at https://megalinter.io/latest/config-file/ and in
# linters documentation

# Enable specific linters for IaC + docs
ENABLE_LINTERS:
  - MARKDOWN_MARKDOWNLINT
  # - MARKDOWN_MARKDOWN_LINK_CHECK  # Can be slow, disabled for speed
  - TERRAFORM_TFLINT
  - TERRAFORM_TERRAFORM_FMT
  # - TERRAFORM_TERRASCAN  # Can be slow, disabled for speed
  # - ANSIBLE_ANSIBLE_LINT  # Temporarily disabled due to structural issues
  - YAML_YAMLLINT
  - JSON_ESLINT_PLUGIN_JSONC
  - BASH_SHELLCHECK

# Global include/exclude filters
FILTER_REGEX_INCLUDE: "docs/|README.md|CHANGELOG.md|infrastructure/|ansible/|packer/|scripts/deployments/"
FILTER_REGEX_EXCLUDE: '(\.git/|\.github/|node_modules/|build/|dist/|vendor/|\.terraform/)'

# Keep rules in-repo for portability
LINTER_RULES_PATH: .github/linters

MARKDOWN_SUMMARY_REPORTER: true
SHOW_ELAPSED_TIME: true
SARIF_REPORTER: true

# Auto-fix settings (disabled by default for safety)
APPLY_FIXES: all

LLM_ADVISOR_ENABLED: true
LLM_PROVIDER: anthropic
LLM_MODEL_NAME: claude-3-7-sonnet-latest
LLM_MAX_TOKENS: 1000
LLM_TEMPERATURE: 0.1
