---
# Main tasks for Docker role

- name: Include OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "default.yml"
      paths:
        - "../vars"
      skip: true

- name: Display Docker installation mode
  debug:
    msg: "Docker installation mode: {{ docker_installation_mode }}"
  when: docker_debug_mode | bool

# Check if Docker is already installed
- name: Check if Docker is installed
  command: which docker
  register: docker_check
  changed_when: false
  failed_when: false

- name: Set Docker installation status
  set_fact:
    docker_is_installed: "{{ docker_check.rc == 0 }}"

# Installation tasks (only if mode is 'install' and Docker not already installed)
- name: Include installation tasks
  include_tasks: installation.yml
  when:
    - docker_installation_mode == 'install'
    - not docker_is_installed

# Configuration tasks (always run)
- name: Include configuration tasks
  include_tasks: configuration.yml
  when: docker_is_installed or docker_installation_mode == 'install'

# User management tasks
- name: Include user management tasks
  include_tasks: users.yml
  when:
    - docker_users_list | length > 0
    - docker_is_installed or docker_installation_mode == 'install'

# Security tasks
- name: Include security configuration tasks
  include_tasks: security.yml
  when:
    - docker_is_installed or docker_installation_mode == 'install'
    - docker_enable_user_namespace_remapping or docker_enable_seccomp

# Resource management tasks
- name: Include resource management tasks
  include_tasks: resources.yml
  when:
    - docker_is_installed or docker_installation_mode == 'install'
    - docker_enable_cleanup_cron

# Firewall compatibility tasks
- name: Include firewall compatibility tasks
  include_tasks: firewall.yml
  when:
    - docker_configure_firewall | bool
    - docker_is_installed or docker_installation_mode == 'install'

# Validation tasks (always run at the end)
- name: Include validation tasks
  include_tasks: validation.yml
  when: docker_is_installed or docker_installation_mode == 'install'

# Generate summary report
- name: Generate installation/validation summary
  include_tasks: summary.yml
  when: docker_is_installed or docker_installation_mode == 'install'
