---
#SPDX-License-Identifier: MIT-0
# VM Diagnostics Role - Default Variables

# Diagnostic Categories Configuration
diagnostic_categories:
  - system
  - network
  - services
  - logs
  - performance
  - troubleshooting

# Diagnostic Depth Settings
diagnostic_depth: "standard"  # basic, standard, comprehensive

# System Diagnostics Configuration
system_diagnostics:
  collect_hardware_info: true
  collect_memory_info: true
  collect_disk_info: true
  collect_network_interfaces: true
  collect_kernel_info: true
  collect_boot_info: true
  ipmi_monitoring: false  # Requires IPMI tools
  smart_disk_checks: true
  filesystem_analysis: true

# Log Collection and Analysis
collect_logs: true
log_collection_paths:
  - /var/log/cloud-init.log
  - /var/log/cloud-init-output.log
  - /var/log/syslog
  - /var/log/auth.log
  - /var/log/kern.log
  - /var/log/dpkg.log
  - /var/log/apt/history.log

log_analysis:
  error_pattern_detection: true
  historical_analysis: true
  log_rotation_check: true
  max_log_size_mb: 100
  retention_days: 30

# Network Diagnostics Configuration
network_diagnostics:
  connectivity_tests: true
  dns_resolution_tests: true
  routing_analysis: true
  firewall_analysis: true
  bandwidth_testing: false  # Can be resource intensive
  interface_diagnostics: true

network_test_targets:
  - "8.8.8.8"
  - "google.com"
  - "github.com"

# Service Diagnostics Configuration
service_diagnostics:
  status_analysis: true
  dependency_analysis: true
  configuration_validation: true
  performance_monitoring: true
  docker_integration: true
  restart_analysis: true

monitored_services:
  - docker
  - ssh
  - systemd-resolved
  - qemu-guest-agent
  - cron
  - rsyslog

# Performance Analysis Configuration
performance_analysis:
  resource_trends: true
  bottleneck_detection: true
  io_testing: false  # Can be disruptive
  memory_leak_detection: true
  historical_data_collection: true
  real_time_monitoring: false

performance_thresholds:
  cpu_usage_warning: 80
  memory_usage_warning: 85
  disk_usage_warning: 90
  load_average_warning: 2.0
  inode_usage_warning: 80

# Troubleshooting Automation Configuration
troubleshooting_automation:
  automated_workflows: true
  common_issue_detection: true
  remediation_recommendations: true
  monitoring_integration: true
  self_healing: false  # Enable with caution

# Output and Reporting Configuration
diagnostic_output_dir: "/tmp/diagnostics"
compress_output: true
generate_report: true
report_format: "json"  # json, yaml, text
retain_diagnostics_days: 7

# Monitoring Tools Integration
enable_monitoring_tools: false  # Install additional monitoring tools
monitoring_tools:
  - htop
  - nethogs
  - ncdu
  - lnav
  - iotop
  - dstat

# Advanced Configuration
advanced_diagnostics:
  kernel_module_analysis: false
  process_tree_analysis: true
  file_descriptor_analysis: true
  socket_analysis: true
  container_diagnostics: true
  virtualization_checks: true

# Security and Safety
security_settings:
  respect_file_permissions: true
  secure_temp_files: true
  no_sensitive_data_collection: true
  audit_diagnostic_access: false

# Performance Impact Control
performance_impact:
  max_concurrent_checks: 5
  check_timeout_seconds: 30
  resource_limit_cpu: 50  # Percentage
  nice_priority: 10  # Lower priority

# Cross-Platform Compatibility
platform_compatibility:
  handle_macos_differences: true
  handle_container_environment: true
  graceful_degradation: true
  skip_unavailable_features: true

# Integration Settings
integration:
  prometheus_metrics: false
  grafana_dashboards: false
  elk_stack_integration: false
  custom_webhooks: []
