---
dependency:
  name: galaxy
  options:
    requirements-file: ../../requirements.yml

driver:
  name: docker

platforms:
  - name: ubuntu-2204
    image: ubuntu:22.04
    dockerfile: Dockerfile
    pre_build_image: false
    privileged: true
    cgroupns_mode: host
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /tmp
    capabilities:
      - SYS_ADMIN

provisioner:
  name: ansible
  inventory:
    host_vars:
      ubuntu-2204:
        ansible_user: root
  playbooks:
    converge: converge.yml
    verify: verify.yml
  config_options:
    defaults:
      callbacks_enabled: ansible.posix.profile_tasks
  env:
    ANSIBLE_VERBOSITY: 1

verifier:
  name: ansible

scenario:
  name: default
  test_sequence:
    - dependency
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
