---
# Process individual firewall rule

- name: Apply firewall rule - {{ rule.name }}
  iptables:
    chain: "{{ chain }}"
    protocol: "{{ rule.protocol }}"
    destination_port: "{{ rule.port }}"
    source: "{{ rule.source | default('0.0.0.0/0') }}"
    jump: ACCEPT
    comment: "{{ rule.comment | default(rule.name) }}"
  when: rule.state == "enabled"
