---
# Docker role handlers

- name: restart docker
  systemd:
    name: docker
    state: restarted
    daemon_reload: true
  become: true
  listen: "restart docker"

- name: reload systemd
  systemd:
    daemon_reload: true
  become: true
  listen: "reload systemd"

- name: reload docker
  systemd:
    name: docker
    state: reloaded
  become: true
  listen: "reload docker"

- name: update grub
  command: update-grub
  become: true
  listen: "update grub"

- name: reload ufw
  ufw:
    state: reloaded
  become: true
  listen: "reload ufw"

- name: reload firewalld
  systemd:
    name: firewalld
    state: reloaded
  become: true
  listen: "reload firewalld"

- name: prune docker system
  command: docker system prune -af --volumes
  become: true
  listen: "prune docker system"
