# MegaLinter Configuration for Sombrero Edge Control
# Central configuration file for all linting rules and settings

# Project information
project:
  name: Sombrero-Edge-Control
  tz: America/New_York
  adrFolder: ./docs/decisions

# Enable specific linters for IaC + docs
ENABLE_LINTERS:
  - MARKDOWN_MARKDOWNLINT
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - TERRAFORM_TFLINT
  - TERRAFORM_TERRAFORM_FMT
  - TERRAFORM_TERRASCAN
  - ANSIBLE_ANSIBLE_LINT
  - YAML_YAMLLINT
  - JSON_ESLINT_PLUGIN_JSONC
  - BASH_SHFMT

# Global include/exclude filters
FILTER_REGEX_INCLUDE: "(docs/|README.md|infrastructure/|ansible/|packer/)"
FILTER_REGEX_EXCLUDE: '(\.git/|\.github/|node_modules/|build/|dist/|vendor/|\.terraform/)'

# Keep rules in-repo for portability
LINTER_RULES_PATH: .github/linters

# Reporter and output settings
REPORT_OUTPUT_FOLDER: report
PRINT_ALPACA: false
SHOW_SKIPPED_LINTERS: true
VALIDATE_ALL_CODEBASE: true

# SARIF reporting for GitHub Security tab
SARIF_REPORTER: true

# Auto-fix settings (disabled by default for safety)
APPLY_FIXES: none
APPLY_FIXES_EVENT: pull_request
APPLY_FIXES_MODE: pull_request
APPLY_FIXES_IF: modified
APPLY_FIXES_IF_SARIF: error

# Terraform-specific settings
TERRAFORM_TFLINT_CONFIG_FILE: .tflint.hcl
TERRAFORM_TERRASCAN_CONFIG_FILE: .terrascan.toml

# Ansible-specific settings
ANSIBLE_ANSIBLE_LINT_CONFIG_FILE: .ansible-lint
