---
# Docker security configuration tasks

- name: Configure user namespace remapping
  block:
    - name: Ensure subuid and subgid files exist
      file:
        path: "{{ item }}"
        state: touch
        mode: '0644'
      loop:
        - /etc/subuid
        - /etc/subgid
      become: true

    - name: Configure dockremap user
      lineinfile:
        path: "{{ item }}"
        line: "dockremap:100000:65536"
        create: true
      loop:
        - /etc/subuid
        - /etc/subgid
      become: true
      notify: restart docker
  when: docker_enable_user_namespace_remapping | bool

- name: Configure seccomp profiles
  block:
    - name: Ensure seccomp directory exists
      file:
        path: /etc/docker/seccomp
        state: directory
        mode: '0755'
      become: true

    - name: Note about seccomp
      debug:
        msg: "Seccomp is enabled by default in Docker. Custom profiles can be added to /etc/docker/seccomp/"
  when: docker_enable_seccomp | bool

- name: Set Docker socket permissions
  file:
    path: /var/run/docker.sock
    mode: "{{ docker_socket_permissions }}"
  become: true
  when: docker_socket.stat.exists | default(false)
