---
# Main tasks file for firewall role

- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family | lower }}.yml"
  failed_when: false

- name: Check if Docker is installed
  ansible.builtin.command: which docker
  register: docker_installed
  changed_when: false
  failed_when: false

- name: Set Docker presence fact
  ansible.builtin.set_fact:
    firewall_docker_present: "{{ docker_installed.rc == 0 }}"

- name: Display Docker compatibility warning
  ansible.builtin.debug:
    msg: |
      ⚠️  WARNING: Docker is {{ 'installed' if firewall_docker_present else 'not installed' }}
      {% if firewall_docker_present %}
      Firewall rules will be configured to work with Docker.
      Custom rules will be added to DOCKER-USER chain.
      Docker's automatic port exposure will bypass host firewall rules!
      {% endif %}
  when: firewall_debug_mode | bool

# Pre-flight checks
- name: Include pre-flight checks
  include_tasks: preflight.yml
  tags:
    - firewall_preflight

# Install required packages
- name: Include installation tasks
  include_tasks: installation.yml
  tags:
    - firewall_install

# Backup existing rules before changes
- name: Include backup tasks
  include_tasks: backup.yml
  when: firewall_create_backup | bool
  tags:
    - firewall_backup

# Configure base firewall rules (legacy method)
- name: Include base configuration tasks (legacy)
  include_tasks: configuration.yml
  when: not firewall_use_priority_rules | default(false)
  tags:
    - firewall_config
    - firewall_legacy

# Configure firewall using priority rules (recommended)
- name: Include priority-based configuration
  include_tasks: priority-rules.yml
  when: firewall_use_priority_rules | default(false)
  tags:
    - firewall_config
    - firewall_priority

# Configure Docker-specific rules if Docker is present
- name: Include Docker compatibility tasks
  include_tasks: docker-compat.yml
  when:
    - firewall_docker_present | bool
    - firewall_docker_compatibility | bool
  tags:
    - firewall_docker

# Configure custom rules
- name: Include custom rules configuration
  include_tasks: custom-rules.yml
  when: firewall_custom_input_rules | length > 0
  tags:
    - firewall_custom

# Configure service-specific chains
- name: Include service chains configuration
  include_tasks: service-chains.yml
  when: firewall_create_service_chains | bool
  tags:
    - firewall_services

# Configure security hardening rules
- name: Include security hardening tasks
  include_tasks: security.yml
  when: firewall_enable | bool
  tags:
    - firewall_security

# Configure persistence
- name: Include persistence configuration
  include_tasks: persistence.yml
  when: firewall_persistent | bool
  tags:
    - firewall_persist

# Validate configuration
- name: Include validation tasks
  include_tasks: validation.yml
  when: firewall_validate_rules | bool
  tags:
    - firewall_validate

# Generate summary report
- name: Include summary tasks
  include_tasks: summary.yml
  when: firewall_export_summary | bool
  tags:
    - firewall_summary
