---
# Summary and reporting tasks

- name: Gather firewall statistics
  ansible.builtin.shell: |
    echo "=== Firewall Configuration Summary ==="
    echo "Date: $(date)"
    echo ""
    echo "Chain Policy Summary:"
    iptables -L -n | grep "^Chain" | grep "policy"
    echo ""
    echo "Rule Counts by Chain:"
    for chain in INPUT OUTPUT FORWARD DOCKER-USER; do
      count=$(iptables -L $chain -n 2>/dev/null | tail -n +3 | wc -l)
      echo "$chain: $count rules"
    done
    echo ""
    echo "Top 10 Rules by Packet Count:"
    iptables -L -n -v | grep -v "^Chain\|^pkts" | sort -rnk1 | head -10
  register: firewall_stats
  changed_when: false

- name: Generate firewall summary report
  copy:
    content: |
      FIREWALL CONFIGURATION SUMMARY
      ==============================
      Generated: {{ ansible_date_time.iso8601 }}
      Host: {{ ansible_hostname }}

      Configuration:
      - Backend: {{ firewall_backend }}
      - Docker Present: {{ firewall_docker_present }}
      - Docker Compatibility: {{ firewall_docker_compatibility }}

      Statistics:
      {{ firewall_stats.stdout }}

      Services:
      {% for rule in firewall_input_rules %}
      - {{ rule.name }} (port {{ rule.port }}): {{ rule.state }}
      {% endfor %}

      {% if firewall_docker_present and firewall_docker_user_rules | length > 0 %}
      Docker-USER Rules:
      {% for rule in firewall_docker_user_rules %}
      - {{ rule.name }}: {{ rule.action | default('DROP') }}
      {% endfor %}
      {% endif %}

      Security Features:
      - Rate Limiting: {{ firewall_enable_rate_limiting }}
      - SYN Flood Protection: {{ firewall_syn_flood_protection }}
      - Port Scan Protection: {{ firewall_port_scan_protection }}
      - Logging: {{ firewall_enable_logging }}

      Files:
      - Rules: /etc/iptables/rules.v4
      - Backups: {{ firewall_rules_backup_dir }}
      - Docker Notes: /etc/iptables/docker-firewall-notes.txt
    dest: "{{ firewall_summary_path | default('/tmp/firewall-summary.txt') }}"
    mode: '0644'

- name: Display summary location
  ansible.builtin.debug:
    msg: "Firewall summary saved to: {{ firewall_summary_path | default('/tmp/firewall-summary.txt') }}"
