---
# Test playbook for vm_smoke_tests role

- name: Test VM Smoke Tests Role
  hosts: localhost
  gather_facts: true

  roles:
    - role: vm_smoke_tests
      vars:
        # Basic test configuration
        smoke_test_phases:
          - system_health
          - service_validation
          - application_health
          - security_validation
          # Skip performance_monitoring in test to avoid disk I/O operations

        # System health thresholds (relaxed for testing)
        max_load_average: 5.0
        min_memory_percent: 1    # Very low for macOS testing
        min_disk_percent: 5
        max_cpu_usage: 90

        # Expected services for testing (empty for macOS compatibility)
        expected_services: []
          # macOS doesn't use systemd services

        # Network tests (using public DNS)
        network_tests:
          - host: "8.8.8.8"
            port: 53
            timeout: 10

        # Expected ports (minimal for testing)
        expected_ports:
          - port: 22
            description: "SSH"
            protocol: "tcp"

        # Test behavior
        test_config:
          fail_fast: false
          collect_debug_info: true
          timeout_default: 15
          retry_count: 2
          retry_delay: 3

        # Reporting settings
        reporting:
          generate_json_report: true
          log_level: "info"
          show_skipped_tests: true

        # Security checks (minimal for testing)
        security_checks:
          ssh_key_only: false      # Disable for testing
          check_sudo_users: true
          verify_firewall: false   # Disable for testing

        # Performance monitoring (basic settings)
        performance_checks:
          enable_resource_monitoring: false  # Disable for testing
          max_response_time: 10000
          min_available_memory_mb: 100
