---
# Check network configuration

- name: Get network configuration from node
  ansible.builtin.uri:
    url: "{{ proxmox_api_url }}/api2/json/nodes/{{ proxmox_node }}/network"
    method: GET
    headers:
      Authorization: "PVEAPIToken={{ proxmox_api_token_id }}={{ proxmox_api_token_secret }}"
    validate_certs: "{{ proxmox_verify_ssl }}"
  register: network_config
  when: api_connectivity_passed | default(false)

- name: Extract network interfaces
  ansible.builtin.set_fact:
    network_interfaces: "{{ network_config.json.data | default([]) }}"
  when:
    - api_connectivity_passed | default(false)
    - network_config is not failed

- name: Check for required bridge
  ansible.builtin.set_fact:
    bridge_exists: "{{ network_interfaces | selectattr('iface', 'equalto', required_bridge) | list | length > 0 }}"
    bridge_info: "{{ network_interfaces | selectattr('iface', 'equalto', required_bridge) | list | first | default({}) }}"
  when:
    - network_interfaces is defined
    - required_bridge is defined

- name: Check VLAN configuration if required
  ansible.builtin.set_fact:
    vlan_configured: true
  when:
    - required_vlan is none or required_vlan == ""

- name: Check specific VLAN if required
  ansible.builtin.set_fact:
    vlan_configured: "{{ network_interfaces | selectattr('iface', 'match', '.*\\.' + (required_vlan | string)) | list | length > 0 }}"
  when:
    - required_vlan is defined
    - required_vlan is not none
    - required_vlan != ""

- name: Set network configuration status
  ansible.builtin.set_fact:
    network_configured: "{{ bridge_exists | default(false) and vlan_configured | default(true) }}"

- name: Display network configuration status
  ansible.builtin.debug:
    msg:
      - "Network Configuration:"
      - "  Required Bridge: {{ required_bridge }}"
      - "  Bridge Exists: {{ 'YES' if bridge_exists | default(false) else 'NO' }}"
      - "  Bridge Active: {{ 'YES' if bridge_info.active | default(false) else 'NO' }}"
      - "  VLAN Required: {{ 'YES (VLAN ' + (required_vlan | string) + ')' if required_vlan else 'NO' }}"
      - "  VLAN Configured: {{ 'YES' if vlan_configured | default(false) else 'N/A' }}"
      - "  Network Ready: {{ 'YES' if network_configured | default(false) else 'NO' }}"

- name: List available bridges if required bridge not found
  ansible.builtin.debug:
    msg:
      - "Available bridges on node {{ proxmox_node }}:"
      - "{{ network_interfaces | selectattr('type', 'equalto', 'bridge') | map(attribute='iface') | list }}"
  when:
    - not (bridge_exists | default(false))
    - network_interfaces is defined

- name: Warn if network not properly configured
  ansible.builtin.debug:
    msg: "WARNING: Network configuration incomplete - deployment may fail"
  when: not (network_configured | default(false))
