---
galaxy_info:
  author: DevOps Team
  description: Research-based development tools installation role for Ubuntu servers
  company: basher83
  license: MIT
  min_ansible_version: "2.9"

  platforms:
    - name: Ubuntu
      versions:
        - focal     # 20.04
        - jammy     # 22.04
        - noble     # 24.04

  galaxy_tags:
    - development
    - tools
    - nodejs
    - python
    - mise
    - uv
    - devops
    - ubuntu
    - productivity

dependencies:
  - src: community.general
    version: ">=8.0.0"
