---
# Development Tools Main Tasks
# Research-based implementation using community.general + custom tasks

- name: Display development tools installation banner
  ansible.builtin.debug:
    msg: |
      ============================================
      Installing Development Tools
      User: {{ devtools_user }}
      Standard packages: {{ devtools_standard_packages | length }}
      Modern tools: mise={{ devtools_mise_enabled }}, uv={{ devtools_uv_enabled }}
      ============================================

- name: Include preflight checks
  ansible.builtin.include_tasks: preflight.yml
  tags:
    - devtools
    - preflight

- name: Install standard development tools
  ansible.builtin.include_tasks: standard-tools.yml
  tags:
    - devtools
    - standard
    - packages
  when: devtools_enabled

- name: Configure Node.js and npm
  ansible.builtin.include_tasks: nodejs.yml
  tags:
    - devtools
    - nodejs
    - npm
  when: devtools_enabled

- name: Configure Python and pip
  ansible.builtin.include_tasks: python.yml
  tags:
    - devtools
    - python
    - pip
  when: devtools_enabled

- name: Install mise version manager
  ansible.builtin.include_tasks: mise.yml
  tags:
    - devtools
    - mise
    - version-manager
  when:
    - devtools_enabled
    - devtools_mise_enabled

- name: Install uv package manager
  ansible.builtin.include_tasks: uv.yml
  tags:
    - devtools
    - uv
    - python
  when:
    - devtools_enabled
    - devtools_uv_enabled

- name: Install additional DevOps tools
  ansible.builtin.include_tasks: additional-tools.yml
  tags:
    - devtools
    - additional
  when: devtools_enabled

- name: Configure shell environment
  ansible.builtin.include_tasks: shell-config.yml
  tags:
    - devtools
    - shell
    - environment
  when:
    - devtools_enabled
    - devtools_configure_shell

- name: Validate installations
  ansible.builtin.include_tasks: validation.yml
  tags:
    - devtools
    - validation
    - verify
  when:
    - devtools_enabled
    - devtools_validate_installation

- name: Generate installation summary
  ansible.builtin.include_tasks: summary.yml
  tags:
    - devtools
    - summary
    - report
  when:
    - devtools_enabled
    - devtools_generate_summary

- name: Display completion message
  ansible.builtin.debug:
    msg: |
      ============================================
      Development Tools Installation Complete!

      Installed tools:
      - Standard packages: ✓
      - Node.js & npm: ✓
      - Python & pip: ✓
      - mise: {{ '✓' if devtools_mise_enabled else '✗' }}
      - uv: {{ '✓' if devtools_uv_enabled else '✗' }}
      - Additional tools: ✓

      Summary: {{ devtools_summary_path }}
      ============================================
