---
# Shell environment configuration

- name: Ensure bashrc exists
  ansible.builtin.file:
    path: "/home/{{ devtools_user }}/.bashrc"
    state: touch
    owner: "{{ devtools_user }}"
    group: "{{ devtools_user }}"
    mode: '0644'
    modification_time: preserve
    access_time: preserve

- name: Add development tools to shell environment
  ansible.builtin.blockinfile:
    path: "/home/{{ devtools_user }}/.bashrc"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - Development Tools"
    block: "{{ devtools_shell_additions | join('\n') }}"
    create: true
  become_user: "{{ devtools_user }}"

- name: Create enhanced bash prompt
  ansible.builtin.blockinfile:
    path: "/home/{{ devtools_user }}/.bashrc"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - Custom Prompt"
    block: |
      # Enhanced bash prompt with git branch info
      parse_git_branch() {
        git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
      }

      # Color definitions
      RED='\033[0;31m'
      GREEN='\033[0;32m'
      YELLOW='\033[1;33m'
      BLUE='\033[0;34m'
      PURPLE='\033[0;35m'
      CYAN='\033[0;36m'
      WHITE='\033[1;37m'
      NC='\033[0m' # No Color

      # Custom prompt with git branch and virtual environment
      PS1="\[${GREEN}\]\u@\h\[${NC}\]:\[${BLUE}\]\w\[${YELLOW}\]\$(parse_git_branch)\[${NC}\]"
      if [ -n "$VIRTUAL_ENV" ]; then
        PS1="($(basename $VIRTUAL_ENV)) $PS1"
      fi
      PS1="$PS1$ "
    create: true
  become_user: "{{ devtools_user }}"

- name: Configure readline for better command line editing
  ansible.builtin.copy:
    content: |
      # Readline configuration for better command line editing
      set editing-mode emacs
      set completion-ignore-case on
      set show-all-if-ambiguous on
      set completion-display-width -1

      # History search
      "\e[A": history-search-backward
      "\e[B": history-search-forward

      # Better tab completion
      set page-completions off
      set completion-query-items 200
      set show-all-if-unmodified on
      set visible-stats on
    dest: "/home/{{ devtools_user }}/.inputrc"
    owner: "{{ devtools_user }}"
    group: "{{ devtools_user }}"
    mode: '0644'

- name: Configure bash history settings
  ansible.builtin.blockinfile:
    path: "/home/{{ devtools_user }}/.bashrc"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - History Settings"
    block: |
      # History settings
      HISTSIZE=10000
      HISTFILESIZE=20000
      HISTCONTROL=ignoreboth:erasedups
      HISTIGNORE="ls:cd:cd -:pwd:exit:date:* --help"

      # Append to history file, don't overwrite
      shopt -s histappend

      # Save multi-line commands as one command
      shopt -s cmdhist

      # Check window size after each command
      shopt -s checkwinsize
    create: true
  become_user: "{{ devtools_user }}"

- name: Create vim configuration for development
  ansible.builtin.copy:
    content: |
      " Basic vim configuration for development
      syntax on
      set number
      set relativenumber
      set tabstop=2
      set shiftwidth=2
      set expandtab
      set autoindent
      set smartindent
      set hlsearch
      set incsearch
      set ignorecase
      set smartcase
      set wildmenu
      set wildmode=list:longest
      set backspace=indent,eol,start
      set ruler
      set showcmd
      set laststatus=2
      set mouse=a

      " File type specific settings
      autocmd FileType python setlocal tabstop=4 shiftwidth=4
      autocmd FileType go setlocal tabstop=4 shiftwidth=4 noexpandtab
      autocmd FileType yaml setlocal tabstop=2 shiftwidth=2

      " Show whitespace
      set listchars=tab:>-,trail:~,extends:>,precedes:<
      set list
    dest: "/home/{{ devtools_user }}/.vimrc"
    owner: "{{ devtools_user }}"
    group: "{{ devtools_user }}"
    mode: '0644'

- name: Create tmux configuration
  ansible.builtin.copy:
    content: |
      # Tmux configuration
      # Set prefix key
      set -g prefix C-a
      unbind C-b
      bind C-a send-prefix

      # Better key bindings
      bind | split-window -h
      bind - split-window -v

      # Mouse support
      set -g mouse on

      # Better colors
      set -g default-terminal "screen-256color"

      # Status bar
      set -g status-bg colour235
      set -g status-fg colour136
      set -g status-left-length 20
      set -g status-left '#[fg=colour166]#h #[fg=colour64]#S '
      set -g status-right '#[fg=colour166]%H:%M %d-%b-%y'

      # Window list colors
      setw -g window-status-current-bg colour166
      setw -g window-status-current-fg colour235

      # Start windows and panes at 1
      set -g base-index 1
      setw -g pane-base-index 1

      # Reload config
      bind r source-file ~/.tmux.conf \; display "Reloaded!"
    dest: "/home/{{ devtools_user }}/.tmux.conf"
    owner: "{{ devtools_user }}"
    group: "{{ devtools_user }}"
    mode: '0644'

- name: Create development workspace directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ devtools_user }}"
    group: "{{ devtools_user }}"
    mode: '0755'
  loop:
    - "/home/{{ devtools_user }}/workspace"
    - "/home/{{ devtools_user }}/scripts"
    - "/home/{{ devtools_user }}/.local/share"
    - "/home/{{ devtools_user }}/.cache"
