---
# Docker daemon configuration tasks

- name: Ensure Docker configuration directory exists
  ansible.builtin.file:
    path: /etc/docker
    state: directory
    mode: '0755'
  become: true

- name: Configure Docker daemon
  copy:
    content: "{{ docker_daemon_options | to_nice_json }}"
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
  notify: restart docker
  when: docker_daemon_options | length > 0

- name: Ensure Docker data directory exists
  ansible.builtin.file:
    path: "{{ docker_data_directory }}"
    state: directory
    owner: root
    group: root
    mode: '0711'
  become: true
  when: docker_data_directory != '/var/lib/docker'

- name: Configure Docker systemd service
  template:
    src: docker.service.j2
    dest: /etc/systemd/system/docker.service.d/override.conf
    owner: root
    group: root
    mode: '0644'
  become: true
  notify:
    - reload systemd
    - restart docker
  when: false  # Disabled by default, enable if custom service config needed

- name: Ensure Docker service is in desired state
  systemd:
    name: docker
    enabled: "{{ docker_service_enabled }}"
    state: "{{ docker_service_state }}"
    daemon_reload: true
  become: true
