---
# Docker validation tasks

- name: Check Docker service status
  systemd:
    name: docker
  register: docker_service_status
  become: true

- name: Verify Docker service is active
  ansible.builtin.assert:
    that:
      - docker_service_status.status.ActiveState == "active"
    fail_msg: "Docker service is not active: {{ docker_service_status.status.ActiveState }}"
    success_msg: "Docker service is active and running"

- name: Check Docker version
  ansible.builtin.command: docker version --format json
  register: docker_version_json
  changed_when: false
  become: true

- name: Parse Docker version information
  ansible.builtin.set_fact:
    docker_version_info: "{{ docker_version_json.stdout | from_json }}"

- name: Verify Docker Compose plugin is installed
  ansible.builtin.command: docker compose version
  register: compose_version
  changed_when: false
  failed_when: false

- name: Check Docker socket permissions
  stat:
    path: /var/run/docker.sock
  register: docker_socket
  become: true

- name: Verify Docker socket permissions
  ansible.builtin.assert:
    that:
      - docker_socket.stat.exists
      - docker_socket.stat.mode == docker_socket_permissions
    fail_msg: "Docker socket has incorrect permissions: {{ docker_socket.stat.mode }}"
    success_msg: "Docker socket permissions are correct"
  when: docker_socket.stat.exists

- name: Test Docker functionality with hello-world
  community.docker.docker_container:
    name: hello-world-test
    image: hello-world
    state: started
    auto_remove: true
  register: hello_world_test
  become: true
  when: "'hello_world_test' in docker_validation_tests"

- name: Check Docker network configuration
  ansible.builtin.command: docker network ls --format json
  register: docker_networks
  changed_when: false
  become: true

- name: Verify default bridge network exists
  ansible.builtin.assert:
    that:
      - docker_networks.stdout | from_json | selectattr('Name', 'equalto', 'bridge') | list | length > 0
    fail_msg: "Default Docker bridge network not found"
    success_msg: "Default Docker bridge network exists"

- name: Collect validation results
  ansible.builtin.set_fact:
    docker_validation_results:
      service_active: "{{ docker_service_status.status.ActiveState == 'active' }}"
      version: "{{ docker_version_info.Client.Version | default('unknown') }}"
      compose_installed: "{{ compose_version.rc == 0 }}"
      compose_version: "{{ compose_version.stdout | default('not installed') }}"
      socket_exists: "{{ docker_socket.stat.exists }}"
      hello_world_success: "{{ hello_world_test.changed | default(false) }}"
      bridge_network_exists: true

- name: Display validation summary
  ansible.builtin.debug:
    msg: |
      Docker Validation Summary:
      - Service Active: {{ docker_validation_results.service_active }}
      - Docker Version: {{ docker_validation_results.version }}
      - Compose Installed: {{ docker_validation_results.compose_installed }}
      - Compose Version: {{ docker_validation_results.compose_version }}
      - Socket Exists: {{ docker_validation_results.socket_exists }}
      - Hello World Test: {{ docker_validation_results.hello_world_success }}
      - Bridge Network: {{ docker_validation_results.bridge_network_exists }}
