---
# Ansible Galaxy requirements file
# Install with: ansible-galaxy collection install -r requirements.yml

collections:
  - name: community.proxmox
    version: ">=1.3.0"
  - name: community.general
    version: ">=8.0.0"
  - name: ansible.posix
    version: ">=1.5.0"
  - name: community.docker
    version: ">=3.0.0"
