---
# Security role handlers

- name: restart sshd
  ansible.builtin.systemd:
    name: sshd
    state: restarted
    daemon_reload: true
  become: true

- name: restart ssh
  ansible.builtin.systemd:
    name: ssh
    state: restarted
    daemon_reload: true
  become: true

- name: reload sysctl
  ansible.builtin.command: sysctl --system
  become: true

- name: restart fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted
    daemon_reload: true
  become: true

- name: restart auditd
  ansible.builtin.command: service auditd restart
  become: true
  # Note: auditd doesn't play well with systemd on some systems

- name: restart rsyslog
  ansible.builtin.systemd:
    name: rsyslog
    state: restarted
    daemon_reload: true
  become: true

- name: restart systemd-journald
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted
    daemon_reload: true
  become: true

- name: restart chrony
  ansible.builtin.systemd:
    name: chrony
    state: restarted
    daemon_reload: true
  become: true

- name: restart apparmor
  ansible.builtin.systemd:
    name: apparmor
    state: restarted
    daemon_reload: true
  become: true

- name: update grub
  ansible.builtin.command: update-grub
  become: true
