---
# Docker installation mode
# Options: 'install' (full installation) or 'validate' (validation only for golden images)
docker_installation_mode: "install"

# Whether Docker is pre-installed (e.g., in golden images)
docker_already_installed: false

# Docker version constraints
docker_version: "24.*"
docker_compose_plugin_version: "*"  # Use latest

# Users to add to docker group
# WARNING: Users in docker group have root-equivalent access
docker_users_list:
  - "{{ ansible_user | default('ansible') }}"

# Docker daemon configuration
docker_daemon_options:
  log-driver: "json-file"
  log-opts:
    max-size: "10m"
    max-file: "3"
  storage-driver: "overlay2"
  exec-opts:
    - "native.cgroupdriver=systemd"
  # Uncomment for user namespace remapping (enhanced security)
  # userns-remap: "default"

# Security configurations
docker_enable_user_namespace_remapping: false
docker_enable_seccomp: true
docker_socket_permissions: "0660"

# Resource management
docker_data_directory: "/var/lib/docker"
docker_enable_cleanup_cron: true
docker_cleanup_schedule: "0 2 * * 0"  # Weekly at 2 AM Sunday
docker_cleanup_flags: "--all --force --volumes"

# Networking
docker_default_bridge_subnet: "172.17.0.0/16"
docker_enable_ipv6: false
docker_dns_servers: []  # Empty = use system DNS

# Service configuration
docker_service_enabled: true
docker_service_state: started
docker_restart_policy: "always"

# Validation settings
docker_validation_tests:
  - engine_version
  - compose_plugin
  - service_status
  - socket_permissions
  - hello_world_test

# Firewall compatibility
# WARNING: Docker requires iptables and is incompatible with pure nftables
docker_configure_firewall: false
docker_preserve_iptables_chains: true

# Package management
docker_apt_release_channel: stable
docker_apt_arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"
docker_apt_gpg_key: https://download.docker.com/linux/ubuntu/gpg
docker_apt_gpg_key_checksum: "sha256:1500c1f56fa9e26b9b8f42452a553675796ade0807cdce11975eb98170b3a570"
docker_apt_repository: >-
  deb [arch={{ docker_apt_arch }} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg]
  https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} {{ docker_apt_release_channel }}

# Monitoring and health checks
docker_enable_health_checks: true
docker_health_check_interval: 60  # seconds

# Debug mode
docker_debug_mode: false
