---
galaxy_info:
  author: DevOps Team
  description: Comprehensive security hardening role for Ubuntu servers
  company: Sombrero Edge Control
  license: MIT
  min_ansible_version: "2.9"

  platforms:
    - name: Ubuntu
      versions:
        - focal     # 20.04
        - jammy     # 22.04
        - noble     # 24.04

  galaxy_tags:
    - security
    - hardening
    - cis
    - ssh
    - fail2ban
    - auditd
    - firewall
    - compliance
    - ubuntu
    - system

dependencies: []
