name: MegaLinter

on:
  pull_request:
    paths:
      - "**/*.md"
      - "**/*.tf"
      - "**/*.hcl"
      - "**/*.yaml"
      - "**/*.yml"
      - "**/*.json"
      - "**/*.sh"
      - "ansible/**"
      - "infrastructure/**"
      - "packer/**"
      - "docs/**"
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  security-events: write
  pull-requests: write

jobs:
  megalinter:
    name: MegaLinter
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: MegaLinter
        id: ml
        uses: oxsecurity/megalinter/flavors/terraform@v8
        env:
          MEGALINTER_FLAVOR: "terraform"
          FILTER_REGEX_INCLUDE: '(docs/|README.md|infrastructure/|ansible/|packer/)'
          FILTER_REGEX_EXCLUDE: '(\.git/|\.github/|node_modules/|build/|dist/|vendor/|\.terraform/)'
          ENABLE_LINTERS: "MARKDOWN_MARKDOWNLINT,TERRAFORM_TFLINT,TERRAFORM_TERRAFORM_FMT,YAML_YAMLLINT,JSON_ESLINT_PLUGIN_JSONC,BASH_SHFMT"
          LINTER_RULES_PATH: .github/linters
          DISABLE_LINTERS: "SPELL_CSPELL"
          SKIP_CLI_LINT_MODES: "project"
          PRINT_ALPACA: "false"
          REPORT_OUTPUT_FOLDER: "${{ github.workspace }}/report"
          SARIF_REPORTER: "true"
          SHOW_ELAPSED_TIME: "true"
          APPLY_FIXES: "none"

      - name: Upload SARIF results
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: report/megalinter-report.sarif
          category: code-quality

      - name: Upload MegaLinter results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: megalinter-results
          path: report/
          retention-days: 30

      - name: Fallback linting (if MegaLinter fails)
        if: failure()
        run: |
          echo "MegaLinter failed, running basic linting checks..."
          pip install yamllint
          echo "Running YAML linting..."
          yamllint . || echo "YAML linting found issues but continuing..."
          echo "Checking for trailing whitespace..."
          find . -name "*.yml" -o -name "*.yaml" -o -name "*.md" | \
            xargs grep -l "[[:space:]]$" || echo "No trailing whitespace found"
          echo "Fallback linting completed"
